name: 'data_repository_tool'
version: '1.0.0'

profile: 'data_repository_tool'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_repository_tool:
    input:
      +materialized: table
      +schema: input
      +pre-hook: ["SET s3_access_key_id='{{ env_var('HMAC_ACCESS_KEY_ID') }}'","SET s3_secret_access_key='{{ env_var('HMAC_SECRET_KEY_VALUE') }}'"]
    staging:
      +materialized: view
      +schema: staging
    output:
      +materialized: table
      +schema: output