data_repository_tool:
  outputs:
    dev:
      type: duckdb
      path: ../../data/dev.duckdb
      threads: 1
      filesystems:
        - fs: gcs
          anon: false

    prod:
      type: duckdb
      path: ../../data/prod.duckdb
      threads: 4

  target: dev
